using System.Collections.Immutable;
using System.Reflection;
using System.Reflection.Emit;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using TUnit.Core.SourceGenerator.CodeGenerators;
using TUnit.Core.SourceGenerator.Generators;
using TUnit.Core.SourceGenerator.Tests.Extensions;

namespace TUnit.Core.SourceGenerator.Tests;

internal sealed class GeneratedEntryPointContractTests
{
    [Test]
    public async Task DesktopModePreservesRegistrationWithoutPublicCatalogRoot()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class DirectCatalogFixture
            {
                [Test]
                public void RunsDirectly() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "GeneratedEntryPointContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            CreateGenerators(),
            parseOptions: new CSharpParseOptions(LanguageVersion.Preview));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var allGenerated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));

        await Assert.That(allGenerated).DoesNotContain("class GeneratedTestEntryPoint");
        await Assert.That(allGenerated).Contains("SourceRegistrar.RegisterEntries");
        await Assert.That(allGenerated).Contains("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("GetGeneratedCases");
        await Assert.That(allGenerated).DoesNotContain("GeneratedTestCase<");
    }

    [Test]
    public async Task ClosedWorldModeOmitsDesktopRegistrationArtifacts()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class ClosedWorldFixture
            {
                [Test]
                public void RunsDirectly() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var generated = generatedCompilation.SyntaxTrees
            .Select(static tree => tree.GetText().ToString())
            .Where(static text => text.Contains("// <auto-generated/>", StringComparison.Ordinal))
            .ToArray();
        var allGenerated = string.Join(Environment.NewLine, generated);

        await Assert.That(allGenerated).Contains("GetCatalogAsync");
        await Assert.That(allGenerated).DoesNotContain("SourceRegistrar");
        await Assert.That(allGenerated).DoesNotContain("Sources.TestEntries");
        await Assert.That(allGenerated).DoesNotContain("ConcurrentDictionary");
        await Assert.That(allGenerated).DoesNotContain("Activator.CreateInstance");
        await Assert.That(allGenerated).DoesNotContain("GetGenericTypeDefinition");
        await Assert.That(allGenerated).DoesNotContain("Type.Name");
        await Assert.That(allGenerated).DoesNotContain("Type.FullName");
        await Assert.That(allGenerated).DoesNotContain("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("MethodMetadata");
        await Assert.That(allGenerated).DoesNotContain("ClassMetadata");
        await Assert.That(allGenerated).DoesNotContain("AsyncConvert");
    }

    [Test]
    public async Task ClosedWorldRootCallGraphUsesTypedCaseDelegates()
    {
        const string source = """
            using TUnit.Core;
            namespace TestProject;
            public sealed class DirectCallGraphFixture
            {
                [Test]
                [Arguments(7)]
                public void Case(long value) { }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var entryPoint = build.Assembly.GetType("TUnit.Generated.GeneratedTestEntryPoint")!;
        var directCatalog = (ITestEntryCatalog) entryPoint
            .GetMethod("GetCatalog", BindingFlags.Public | BindingFlags.Static)!
            .Invoke(null, null)!;
        await Assert.That(directCatalog.GetGeneratedCases()).IsNotEmpty();
        var roots = new MethodBase?[]
        {
            entryPoint.GetMethod("GetCatalog", BindingFlags.Public | BindingFlags.Static),
            entryPoint.GetMethod("GetCatalogAsync", BindingFlags.Public | BindingFlags.Static),
            entryPoint.TypeInitializer,
        }.OfType<MethodBase>();
        var visited = new HashSet<MethodBase>();
        var pending = new Queue<MethodBase>(roots);
        var forbidden = new List<string>();

        while (pending.Count > 0)
        {
            var method = pending.Dequeue();
            if (!visited.Add(method))
            {
                continue;
            }

            foreach (var member in GetReferencedMembers(method))
            {
                var identity = member switch
                {
                    Type type => type.FullName ?? type.Name,
                    MethodBase referencedMethod => referencedMethod.DeclaringType?.FullName + "." + referencedMethod.Name,
                    _ => member.DeclaringType?.FullName + "." + member.Name,
                };
                if (IsDesktopActivationSymbol(identity))
                {
                    forbidden.Add(identity);
                }

                if (member is MethodBase referenced && referenced.DeclaringType?.Assembly == build.Assembly)
                {
                    pending.Enqueue(referenced);
                }
            }
        }

        await Assert.That(forbidden).IsEmpty()
            .Because(string.Join(Environment.NewLine, forbidden));
    }

    [Test]
    public async Task ClosedWorldGenericAndMultiMethodSourcesCompileAsDirectCases()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            [GenerateGenericTest(typeof(int))]
            [GenerateGenericTest(typeof(string))]
            public sealed class GenericCatalogFixture<T>
            {
                [Test]
                public void First() { }

                [Test]
                public void Second() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldGenericCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var allGenerated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));
        await Assert.That(allGenerated).Contains("GeneratedTestCase<global::TestProject.GenericCatalogFixture<int>>");
        await Assert.That(allGenerated).Contains("GeneratedTestCase<global::TestProject.GenericCatalogFixture<string>>");
        await Assert.That(allGenerated).Contains("First");
        await Assert.That(allGenerated).Contains("Second");
        await Assert.That(allGenerated).DoesNotContain("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("MethodMetadata");
        await Assert.That(allGenerated).DoesNotContain("ClassMetadata");
        await Assert.That(allGenerated).DoesNotContain("SourceRegistrar");
        await Assert.That(allGenerated).DoesNotContain("Activator.CreateInstance");
    }

    [Test]
    public async Task DesktopGenericSourcesRemainInTheUpstreamRegistrationPipeline()
    {
        const string source = """
            using TUnit.Core;
            namespace TestProject;
            [GenerateGenericTest(typeof(int))]
            [GenerateGenericTest(typeof(string))]
            public sealed class DesktopGenericCatalogFixture<T>
            {
                [Test]
                public void First() { }

                [Test]
                public void Second() { }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: false);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases).IsEmpty();
        await Assert.That(build.Assembly.GetType("TUnit.Generated.GeneratedTestEntryPoint")).IsNull();
    }

    [Test]
    public async Task ClosedWorldRootReferencesInheritedSourcesWithoutDirectTests()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public class BaseCatalogFixture
            {
                [Before(HookType.Class)]
                public static void BaseClassSetup() { }

                [After(HookType.Class)]
                public static void BaseClassTeardown() { }

                [Test]
                public void InheritedCase() { }
            }

            [InheritsTests]
            public sealed class DerivedCatalogFixture : BaseCatalogFixture
            {
                [Before(HookType.Class)]
                public static void DerivedClassSetup() { }

                [After(HookType.Class)]
                public static void DerivedClassTeardown() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldInheritedCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var entryPoint = generatedCompilation.SyntaxTrees
            .Select(static tree => tree.GetText().ToString())
            .Single(static text => text.Contains("class GeneratedTestEntryPoint", StringComparison.Ordinal));
        await Assert.That(entryPoint).Contains("DerivedCatalogFixture");
        await Assert.That(entryPoint).Contains("InheritedCase");

        var generated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees
                .Select(static tree => tree.GetText().ToString())
                .Where(static text => text.Contains("global::TestProject.DerivedCatalogFixture", StringComparison.Ordinal)));
        await Assert.That(generated.IndexOf("BaseClassSetup", StringComparison.Ordinal))
            .IsLessThan(generated.IndexOf("DerivedClassSetup", StringComparison.Ordinal));
        await Assert.That(generated.IndexOf("DerivedClassTeardown", StringComparison.Ordinal))
            .IsLessThan(generated.IndexOf("BaseClassTeardown", StringComparison.Ordinal));
        await Assert.That(generated.IndexOf("GeneratedLifecycleStage.ClassSetup", StringComparison.Ordinal))
            .IsLessThan(generated.IndexOf("GeneratedLifecycleStage.ClassTeardown", StringComparison.Ordinal));
        await Assert.That(generated).Contains("\"global::TestProject.DerivedCatalogFixture\"");
    }

    [Test]
    public async Task ClosedWorldReportsUnsupportedAuthoredCapabilities()
    {
        const string source = """
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using TUnit.Core;
            using TUnit.Core.Interfaces;

            [assembly: ClassConstructor(typeof(object))]

            namespace TestProject;

            public sealed class UnsupportedCatalogFixture
            {
                [Test]
                [MethodDataSource(nameof(Data))]
                public void RuntimeData(int value) { }

                [Test]
                public CustomAwaitable CustomAwaitable() => new();

                [Test]
                [Arguments(1)]
                public void Narrowing(byte value) { }

                [Test]
                [Skip("unsupported")]
                [Explicit]
                [Retry(1)]
                [Timeout(100)]
                [ParallelGroup("unsupported")]
                public void UnsupportedExecutionSemantics() { }

                [Test]
                [FutureSemantic]
                public void FutureSemanticCase() { }

                [Before(HookType.Test)]
                public void ContextHook(TestContext context) { }

                [Before(HookType.Test)]
                public void UnsupportedHookParameter(string value) { }

                [Before(HookType.Assembly)]
                public static void AssemblyHook() { }

                [BeforeEvery(HookType.Test)]
                public static void GlobalHook() { }

                [DynamicTestBuilder]
                public void DynamicBuilder() { }

                [MethodDataSource(nameof(Data))]
                public int Injected { get; set; }

                [Arguments(2)]
                public int ArgumentInjected { get; set; }

                [Arguments(3)]
                public static int StaticArgumentInjected { get; set; }

                public static IEnumerable<int> Data() => new[] { 1 };
            }

            public sealed class CustomAwaitable { }

            [ClassDataSource(typeof(RuntimeClassData))]
            public sealed class RuntimeClassDataFixture { }

            public sealed class RuntimeClassData { }

            public sealed class InitializableFixture : IAsyncInitializer
            {
                public Task InitializeAsync() => Task.CompletedTask;
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
            public sealed class FutureSemanticAttribute : global::TUnit.Core.TUnitAttribute;
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldUnsupportedCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(static diagnostic => diagnostic.ToString())
            .ToArray();
        var generated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));

        await Assert.That(errors.Any(static error => error.Contains("Runtime data source", StringComparison.Ordinal))).IsFalse();
        await Assert.That(errors.Any(static error => error.Contains("return void, Task, or ValueTask", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("TestContext or ClassHookContext", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("may only inject CancellationToken", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Dynamic test builders", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Property data injection", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Assembly, test-session", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Global lifecycle hooks", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Runtime class data source", StringComparison.Ordinal))).IsFalse();
        await Assert.That(errors.Any(static error => error.Contains("IAsyncInitializer", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Assembly-level runtime class construction", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Argument conversion", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("TUnit semantic attribute 'SkipAttribute'", StringComparison.Ordinal))).IsFalse();
        await Assert.That(errors.Any(static error => error.Contains("TUnit semantic attribute 'RetryAttribute'", StringComparison.Ordinal))).IsFalse();
        await Assert.That(errors.Any(static error => error.Contains("TUnit semantic attribute 'ParallelGroupAttribute'", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("TUnit semantic attribute 'FutureSemanticAttribute'", StringComparison.Ordinal))).IsTrue();
        await Assert.That(generated).DoesNotContain("AsyncConvert");
        await Assert.That(generated).Contains("Generated catalog supports only void, Task, and ValueTask");
    }

    [Test]
    public async Task ClosedWorldAllowsExactAndImplicitConstantArguments()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class SupportedArgumentsFixture
            {
                [Test]
                [Arguments(1)]
                public void Widening(long value) { }

                [Test]
                [Arguments("ready")]
                public void Text(string value) { }

                [Test]
                [Arguments(null)]
                public void Nullable(string? value) { }

                [Test]
                [Arguments(Mode.First)]
                public void Enum(Mode value) { }

            }

            public enum Mode
            {
                First,
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldSupportedArgumentsContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));
    }

    [Test]
    public async Task ClosedWorldPreservesOptionalArgumentDefaults()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class OptionalMethodFixture
            {
                [Test]
                [Arguments()]
                public void MethodDefault(int value = 17)
                {
                    if (value != 17) throw new System.InvalidOperationException();
                }
            }

            [Arguments()]
            public sealed class OptionalConstructorFixture(int value = 17)
            {
                [Test]
                public void ConstructorDefault()
                {
                    if (value != 17) throw new System.InvalidOperationException();
                }
            }

            [Arguments(3, 4)]
            public sealed class ParamsConstructorFixture(params int[] values)
            {
                [Test]
                public void ConstructorParams()
                {
                    if (values.Length != 2 || values[0] != 3 || values[1] != 4)
                        throw new System.InvalidOperationException();
                }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases.Count).IsEqualTo(3);
        foreach (var testCase in cases)
        {
            await testCase.ExecuteAsync();
        }
    }

    [Test]
    public async Task ClosedWorldEmitsTypedArgumentsRowsForMethodAndClassForms()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class TypedMethodArgumentsFixture
            {
                [Test]
                [Arguments<int>(7)]
                public void MethodValue(int value)
                {
                    if (value != 7) throw new System.InvalidOperationException("method value was not emitted");
                }
            }

            [Arguments<string>("ready")]
            public sealed class TypedConstructorArgumentsFixture(string value)
            {
                [Test]
                public void ConstructorValue()
                {
                    if (value != "ready") throw new System.InvalidOperationException("constructor value was not emitted");
                }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases.Count).IsEqualTo(2);
        foreach (var testCase in cases)
        {
            await testCase.ExecuteAsync();
        }
    }

    [Test]
    public async Task ClosedWorldPreservesMethodDisplayNameAndRowSubstitution()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class DisplayNameFixture
            {
                [Test]
                [DisplayName("Date $arg1 $value $valued $arg3")]
                [Arguments(7, DisplayName = "row display must lose")]
                public void Case(int value) { }

                [Test]
                [Arguments("x", 2, DisplayName = "row $arg1/$arg2/$arg3/$arg1x/$first/$second/$firstExtra")]
                public void RowDisplay(string first, int second) { }
            }

            [DisplayName("Class $text $arg1")]
            [Arguments("ready", DisplayName = "constructor row must lose")]
            public sealed class ClassDisplayNameFixture(string text)
            {
                [Test]
                public void Case() { }
            }

            [Arguments("ready", DisplayName = "constructor row $arg1/$text")]
            public sealed class ConstructorRowDisplayNameFixture(string text)
            {
                [Test]
                [Arguments(3)]
                public void Case(int value) { }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases.Count).IsEqualTo(4);
        await Assert.That(cases.Select(static testCase => testCase.DisplayName)
                .OrderBy(static displayName => displayName, StringComparer.Ordinal)
                .SequenceEqual(new[]
                {
                    "Class ready $arg1",
                    "Date $arg1 7 7d $arg3",
                    "constructor row 3/$text",
                    "row x/2/$arg3/$arg1x/x/2/$firstExtra",
                }))
            .IsTrue();
    }

    [Test]
    public async Task DesktopModeKeepsConversionBackedArgumentsInTheUpstreamPipeline()
    {
        const string source = """
            using System;
            using TUnit.Core;

            namespace TestProject;

            public sealed class ConversionFixture
            {
                [Test]
                [Arguments("2022-05-31")]
                public void DateTimeFromString(DateTime value) { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "DesktopConversionContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            CreateGenerators(),
            parseOptions: new CSharpParseOptions(LanguageVersion.Preview));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var allGenerated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));
        await Assert.That(allGenerated).Contains("SourceRegistrar.RegisterEntries");
        await Assert.That(allGenerated).Contains("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("GetGeneratedCases");
        await Assert.That(allGenerated).DoesNotContain("GeneratedTestCase<");

        using var stream = new MemoryStream();
        var emitResult = generatedCompilation.Emit(stream);
        await Assert.That(emitResult.Success).IsTrue()
            .Because(string.Join(Environment.NewLine,
                emitResult.Diagnostics.Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                    .Select(static diagnostic => diagnostic.ToString())));
    }

    [Test]
    public async Task ClosedWorldCatalogCarriesInheritedExecutionAndRowMetadata()
    {
        const string source = """
            using TUnit.Core;
            using TUnit.Core.Enums;

            [assembly: Category("assembly")]
            [assembly: Property("assembly", "yes")]
            [assembly: Timeout(900)]
            [assembly: Retry(1)]

            namespace TestProject;

            [Category("base")]
            [Property("base", "yes")]
            [Repeat(2)]
            [Timeout(500)]
            [Retry(2, BackoffMs = 7, BackoffMultiplier = 3.0,
                RetryOnExceptionTypes = new[] { typeof(System.InvalidOperationException) })]
            [ExecutionPriority(Priority.High)]
            public class BaseFixture
            {
                [Before(HookType.Test)]
                [Timeout(25)]
                public void Setup() { }

                [Test]
                public void Prerequisite() { }

                [Test]
                [Arguments(7, Skip = "row skip", Categories = new[] { "row" })]
                [Category("method")]
                [Property("method", "yes")]
                [DependsOn(nameof(Prerequisite))]
                public void Repeated(int value) { }
            }

            [InheritsTests]
            [Category("derived")]
            [Explicit]
            [NotDiscoverable]
            public sealed class DerivedFixture : BaseFixture;
            """;

        var cases = BuildGeneratedCatalog(source, closedWorld: true)
            .Catalog
            .GetGeneratedCases()
            .Where(static testCase =>
                testCase.GroupIdentity.Contains("DerivedFixture", StringComparison.Ordinal) &&
                testCase.MethodName == "Repeated")
            .OrderBy(static testCase => testCase.RepeatIndex)
            .ToArray();

        await Assert.That(cases.Count).IsEqualTo(3);
        await Assert.That(cases.Select(static testCase => testCase.RepeatIndex)).IsEquivalentTo([0, 1, 2]);
        await Assert.That(cases.Select(static testCase => testCase.StableId).Distinct().Count()).IsEqualTo(3);
        foreach (var testCase in cases)
        {
            await Assert.That(testCase.Timeout).IsEqualTo(TimeSpan.FromMilliseconds(500));
            await Assert.That(testCase.RetryPolicy.MaxRetries).IsEqualTo(2);
            await Assert.That(testCase.RetryPolicy.BackoffMilliseconds).IsEqualTo(7);
            await Assert.That(testCase.RetryPolicy.BackoffMultiplier).IsEqualTo(3.0);
            await Assert.That(testCase.RetryPolicy.Accepts(new InvalidOperationException())).IsTrue();
            await Assert.That(testCase.RetryPolicy.Accepts(new ArgumentException())).IsFalse();
            await Assert.That(testCase.SkipReason).IsEqualTo("row skip");
            await Assert.That(testCase.ExecutionPriority).IsEqualTo((int) TUnit.Core.Enums.Priority.High);
            await Assert.That(testCase.IsExplicit).IsTrue();
            await Assert.That(testCase.IsNotDiscoverable).IsTrue();
            await Assert.That(testCase.Categories).IsEquivalentTo(["assembly", "base", "derived", "method", "row"]);
            await Assert.That(testCase.Properties).IsEquivalentTo(["assembly=yes", "base=yes", "method=yes"]);
            await Assert.That(testCase.Dependencies).Contains(":Prerequisite");
            await Assert.That(testCase.Lifecycle.Actions.Single(static action =>
                    action.Stage == GeneratedLifecycleStage.TestSetup).Timeout)
                .IsEqualTo(TimeSpan.FromMilliseconds(25));
        }
    }

    [Test]
    public async Task ClosedWorldCatalogMaterializesStaticMethodPropertyFieldAndAsyncDataSources()
    {
        const string source = """
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using TUnit.Core;

            namespace TestProject;

            public sealed class ExternalData
            {
                public static IEnumerable<(int, string)> Tuples()
                {
                    yield return (1, "one");
                    yield return (2, "two");
                }

                public static int[] Values => new[] { 3, 4 };

                public static readonly Task<int[]> AsyncValues = Task.FromResult(new[] { 5, 6 });

                public static async IAsyncEnumerable<int> Stream()
                {
                    yield return 7;
                    await Task.CompletedTask;
                }

                public static ValueTask<int> Scalar() => ValueTask.FromResult(8);

                public static int[] Empty => [];
            }

            public sealed class MethodDataFixture
            {
                public static readonly List<string> Seen = [];

                [Test]
                [MethodDataSource<ExternalData>(nameof(ExternalData.Tuples))]
                public void TupleCase(int value, string text) => Seen.Add($"tuple:{value}:{text}");

                [Test]
                [MethodDataSource(typeof(ExternalData), nameof(ExternalData.Values))]
                public void PropertyCase(int value) => Seen.Add($"property:{value}");

                [Test]
                [MethodDataSource<ExternalData>(nameof(ExternalData.AsyncValues))]
                public void FieldCase(int value) => Seen.Add($"field:{value}");

                [Test]
                [MethodDataSource<ExternalData>(nameof(ExternalData.Stream))]
                public void AsyncEnumerableCase(int value) => Seen.Add($"stream:{value}");

                [Test]
                [Repeat(1)]
                [MethodDataSource<ExternalData>(nameof(ExternalData.Scalar))]
                public void ScalarCase(int value) => Seen.Add($"scalar:{value}");

                [Test]
                [MethodDataSource<ExternalData>(nameof(ExternalData.Empty), SkipIfEmpty = true)]
                public void EmptyCase(int value) => Seen.Add($"empty:{value}");
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases()
            .Where(static testCase => testCase.GroupIdentity.Contains("MethodDataFixture", StringComparison.Ordinal))
            .ToArray();

        await Assert.That(cases.Count).IsEqualTo(10);
        await Assert.That(cases.Select(static testCase => testCase.StableId).Distinct().Count()).IsEqualTo(10);
        var emptyCase = cases.Single(static testCase => testCase.MethodName == "EmptyCase");
        await Assert.That(emptyCase.SkipReason).Contains("produced no rows");
        foreach (var testCase in cases.Where(static testCase => testCase.SkipReason is null))
        {
            await testCase.ExecuteAsync();
        }

        var fixture = build.Assembly.GetType("TestProject.MethodDataFixture")!;
        var seen = (List<string>) fixture.GetField("Seen", BindingFlags.Public | BindingFlags.Static)!.GetValue(null)!;
        await Assert.That(seen).IsEquivalentTo([
            "tuple:1:one",
            "tuple:2:two",
            "property:3",
            "property:4",
            "field:5",
            "field:6",
            "stream:7",
            "scalar:8",
            "scalar:8",
        ]);
    }

    [Test]
    public async Task ClosedWorldCatalogKeepsMixedSourceKindsDistinctAndPreservesConstructorMetadata()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class Data { }

            [Arguments(null)]
            [ClassDataSource<Data>]
            public sealed class MixedConstructorFixture(Data data)
            {
                public static int[] Values() => [1];

                [Test]
                [MethodDataSource(nameof(Values))]
                public void Case(int value) { }
            }

            [ClassDataSource<Data>]
            public sealed class MixedMethodFixture(Data data)
            {
                [Test]
                [Arguments(null)]
                [ClassDataSource<Data>]
                public void Case(Data methodData) { }
            }

            [Arguments(1, Skip = "constructor skip", Categories = new[] { "row" })]
            public sealed class ConstructorMetadataFixture(int constructorValue)
            {
                public static int[] Values() => [1];

                [Test]
                [MethodDataSource(nameof(Values))]
                public void Case(int value) { }
            }

            [Arguments(null, Skip = "class constructor skip", Categories = new[] { "class-row" })]
            public sealed class ClassConstructorMetadataFixture(Data constructorData)
            {
                [Test]
                [ClassDataSource<Data>]
                public void Case(Data methodData) { }
            }
            """;

        var cases = BuildGeneratedCatalog(source, closedWorld: true).Catalog.GetGeneratedCases();

        await Assert.That(cases.Count).IsEqualTo(6);
        await Assert.That(cases.Select(static testCase => testCase.StableId).Distinct(StringComparer.Ordinal).Count())
            .IsEqualTo(6);
        var metadataCase = cases.Single(static testCase =>
            testCase.SkipReason == "constructor skip");
        await Assert.That(metadataCase.SkipReason).IsEqualTo("constructor skip");
        await Assert.That(metadataCase.Categories).Contains("row");
        var classMetadataCase = cases.Single(static testCase =>
            testCase.SkipReason == "class constructor skip");
        await Assert.That(classMetadataCase.SkipReason).IsEqualTo("class constructor skip");
        await Assert.That(classMetadataCase.Categories).Contains("class-row");
    }

    [Test]
    public async Task ClosedWorldCatalogTreatsEmptySkipAsSkipAndRejectsNegativeRepeat()
    {
        const string emptySkipSource = """
            using TUnit.Core;
            namespace TestProject;
            public sealed class Fixture
            {
                [Test]
                [Skip("")]
                public void Case() { }
            }
            """;
        var skipped = BuildGeneratedCatalog(emptySkipSource, closedWorld: true)
            .Catalog
            .GetGeneratedCases()
            .Single();
        await Assert.That(skipped.SkipReason).IsEqualTo(string.Empty);

        const string negativeRepeatSource = """
            using TUnit.Core;
            namespace TestProject;
            public sealed class Fixture
            {
                [Test]
                [Repeat(-1)]
                public void Case() { }
            }
            """;
        InvalidOperationException? failure = null;
        try
        {
            BuildGeneratedCatalog(negativeRepeatSource, closedWorld: true);
        }
        catch (InvalidOperationException exception)
        {
            failure = exception;
        }

        await Assert.That(failure).IsNotNull();
        await Assert.That(failure!.Message).Contains("Repeat count cannot be negative");
    }

    [Test]
    public async Task ClosedWorldCatalogCreatesClassDataLazilyPerLogicalCaseAndDisposesItOnce()
    {
        const string source = """
            using System;
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using TUnit.Core;

            namespace TestProject;

            public sealed class ConstructorResource : IDisposable, IAsyncDisposable
            {
                public static int Created;
                public static int AsyncDisposed;
                public static int SyncDisposed;

                public ConstructorResource() => Created++;
                public void Dispose() => SyncDisposed++;
                public ValueTask DisposeAsync()
                {
                    AsyncDisposed++;
                    return default;
                }
            }

            public sealed class MethodResource : IDisposable, IAsyncDisposable
            {
                public static int Created;
                public static int AsyncDisposed;
                public static int SyncDisposed;

                public MethodResource() => Created++;
                public void Dispose() => SyncDisposed++;
                public ValueTask DisposeAsync()
                {
                    AsyncDisposed++;
                    return default;
                }
            }

            [ClassDataSource<ConstructorResource>]
            public sealed class ClassDataFixture(ConstructorResource constructorResource)
            {
                public static readonly List<bool> Observed = [];

                [Test]
                [Repeat(1)]
                [ClassDataSource<MethodResource>]
                public void Case(MethodResource methodResource) =>
                    Observed.Add(constructorResource is not null && methodResource is not null);
            }

            public sealed class ParameterClassDataFixture
            {
                [Test]
                public void Case([ClassDataSource<MethodResource>] MethodResource methodResource) =>
                    ClassDataFixture.Observed.Add(methodResource is not null);
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases()
            .Where(static testCase => testCase.GroupIdentity.Contains("TestProject.ClassDataFixture", StringComparison.Ordinal))
            .OrderBy(static testCase => testCase.RepeatIndex)
            .ToArray();
        var constructorResource = build.Assembly.GetType("TestProject.ConstructorResource")!;
        var methodResource = build.Assembly.GetType("TestProject.MethodResource")!;

        await Assert.That(cases.Count).IsEqualTo(2);
        await Assert.That((int) constructorResource.GetField("Created")!.GetValue(null)!).IsEqualTo(0);
        await Assert.That((int) methodResource.GetField("Created")!.GetValue(null)!).IsEqualTo(0);

        foreach (var testCase in cases)
        {
            await testCase.ExecuteAsync();
            await testCase.DisposeDataAsync();
            await testCase.DisposeDataAsync();
        }

        await Assert.That((int) constructorResource.GetField("Created")!.GetValue(null)!).IsEqualTo(2);
        await Assert.That((int) methodResource.GetField("Created")!.GetValue(null)!).IsEqualTo(2);
        await Assert.That((int) constructorResource.GetField("AsyncDisposed")!.GetValue(null)!).IsEqualTo(2);
        await Assert.That((int) methodResource.GetField("AsyncDisposed")!.GetValue(null)!).IsEqualTo(2);
        await Assert.That((int) constructorResource.GetField("SyncDisposed")!.GetValue(null)!).IsEqualTo(0);
        await Assert.That((int) methodResource.GetField("SyncDisposed")!.GetValue(null)!).IsEqualTo(0);
        var fixture = build.Assembly.GetType("TestProject.ClassDataFixture")!;
        var observed = (List<bool>) fixture.GetField("Observed")!.GetValue(null)!;
        await Assert.That(observed).IsEquivalentTo([true, true]);

        var parameterCase = build.Catalog.GetGeneratedCases().Single(static testCase =>
            testCase.GroupIdentity.Contains("ParameterClassDataFixture", StringComparison.Ordinal));
        await parameterCase.ExecuteAsync();
        await parameterCase.DisposeDataAsync();
        await Assert.That((int) methodResource.GetField("Created")!.GetValue(null)!).IsEqualTo(3);
        await Assert.That((int) methodResource.GetField("AsyncDisposed")!.GetValue(null)!).IsEqualTo(3);
    }

    [Test]
    public async Task ClosedWorldCatalogReportsPreciseInvalidDataSourceShapes()
    {
        const string source = """
            using TUnit.Core;
            namespace TestProject;

            public sealed class InstanceProviderFixture
            {
                [Test]
                [MethodDataSource(nameof(Data))]
                public void Case(int value) { }
                public int[] Data() => [1];
            }

            public sealed class DeferredProviderFixture
            {
                [Test]
                [MethodDataSource(nameof(Data), DeferEnumeration = true)]
                public void Case(int value) { }
                public static int[] Data() => [1];
            }

            public sealed class AmbiguousProviderFixture
            {
                [Test]
                [MethodDataSource(nameof(Data))]
                public void Case(int value) { }
                public static int[] Data(int value = 1) => [value];
                public static int[] Data(long value = 1) => [(int)value];
            }

            public sealed class SharedProviderFixture
            {
                [Test]
                [ClassDataSource<Resource>(Shared = SharedType.PerClass)]
                public void Case(Resource value) { }
            }

            public sealed class Resource { }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldInvalidDataSources",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);
        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(static diagnostic => diagnostic.ToString())
            .ToArray();

        await Assert.That(errors.Any(static error => error.Contains(
            "must resolve to an accessible static method, property, or field", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains(
            "DeferEnumeration=true is not supported", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains(
            "is ambiguous for the supplied arguments", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains(
            "use SharedType.None", StringComparison.Ordinal))).IsTrue();
    }

    private static GeneratedCatalogBuild BuildGeneratedCatalog(string source, bool closedWorld)
    {
        var compilation = CSharpCompilation.Create(
                closedWorld ? "ClosedWorldCatalogParity" : "DesktopCatalogParity",
                [CSharpSyntaxTree.ParseText(
                    source,
                    new CSharpParseOptions(LanguageVersion.Preview),
                    path: "CatalogParityFixture.cs")],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            CreateGenerators(),
            parseOptions: new CSharpParseOptions(LanguageVersion.Preview));
        if (closedWorld)
        {
            driver = driver.WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        }

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);
        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        if (errors.Length > 0)
        {
            throw new InvalidOperationException(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));
        }

        using var stream = new MemoryStream();
        var emitResult = generatedCompilation.Emit(stream);
        if (!emitResult.Success)
        {
            throw new InvalidOperationException(string.Join(Environment.NewLine,
                emitResult.Diagnostics.Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                    .Select(static diagnostic => diagnostic.ToString())));
        }

        var assembly = System.Reflection.Assembly.Load(stream.ToArray());
        var generatedCases = assembly.GetTypes()
            .Where(static type => type.Namespace == "TUnit.Generated")
            .SelectMany(static type => type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                .Where(static method => method.Name == "GetGeneratedCases" &&
                                        method.ReturnType == typeof(GeneratedTestCase[])))
            .SelectMany(static method => (GeneratedTestCase[]) method.Invoke(null, null)!)
            .ToArray();

        return new GeneratedCatalogBuild(
            assembly,
            new SourceGeneratedTestCatalog(generatedCases, "TUnit.Core.SourceGenerator"));
    }

    private static async Task<string[]> ExecuteCatalog(SourceGeneratedTestCatalog catalog)
    {
        var results = new List<string>();
        foreach (var testCase in catalog.GetGeneratedCases())
        {
            try
            {
                await testCase.ExecuteAsync();
                results.Add($"{testCase.StableId}:Passed");
            }
            catch (Exception exception)
            {
                results.Add($"{testCase.StableId}:{exception.GetType().Name}");
            }
        }

        return results.ToArray();
    }

    private static string DescribeCase(GeneratedTestCase testCase)
    {
        var arguments = string.Join(",", testCase.Arguments.Select(static argument =>
            argument switch
            {
                null => "null",
                string text => text,
                _ => Convert.ToString(argument, System.Globalization.CultureInfo.InvariantCulture) ?? "null",
            }));
        var lifecycle = string.Join(",", testCase.Lifecycle.Actions.Select(static action => $"{action.Stage}:{action.Order}"));
        return string.Join("|", testCase.StableId, testCase.DisplayName, testCase.GroupIdentity,
            testCase.InvocationKind, testCase.CompletionPolicy, testCase.CatalogProvenance, arguments, lifecycle);
    }

    private sealed record GeneratedCatalogBuild(System.Reflection.Assembly Assembly, SourceGeneratedTestCatalog Catalog);

    private static bool IsDesktopActivationSymbol(string identity)
    {
        return identity.Contains("CastHelper", StringComparison.Ordinal) ||
               identity.Contains("Activator", StringComparison.Ordinal) ||
               identity.Contains("ConcurrentDictionary", StringComparison.Ordinal) ||
               identity.Contains("MethodInfo", StringComparison.Ordinal) ||
               identity.Contains("System.Reflection", StringComparison.Ordinal) ||
               identity.Contains("DynamicInvoke", StringComparison.Ordinal) ||
               identity.Contains("SourceRegistrar", StringComparison.Ordinal) ||
               identity.Contains("TestEntryFactory", StringComparison.Ordinal) ||
               identity.Contains("MethodMetadata", StringComparison.Ordinal) ||
               identity.Contains("ClassMetadata", StringComparison.Ordinal) ||
               identity.Contains("AsyncConvert", StringComparison.Ordinal);
    }

    private static IEnumerable<MemberInfo> GetReferencedMembers(MethodBase method)
    {
        var body = method.GetMethodBody();
        var il = body?.GetILAsByteArray();
        if (il is null)
        {
            yield break;
        }

        var singleByteOpCodes = new OpCode[0x100];
        var doubleByteOpCodes = new OpCode[0x100];
        foreach (var field in typeof(OpCodes).GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            if (field.GetValue(null) is not OpCode opCode)
            {
                continue;
            }

            var value = unchecked((ushort) opCode.Value);
            if (value < 0x100)
            {
                singleByteOpCodes[value] = opCode;
            }
            else if ((value & 0xff00) == 0xfe00)
            {
                doubleByteOpCodes[value & 0xff] = opCode;
            }
        }

        var module = method.Module;
        var typeArguments = method.DeclaringType?.IsGenericType == true
            ? method.DeclaringType.GetGenericArguments()
            : null;
        var methodArguments = method is MethodInfo { IsGenericMethod: true } genericMethod
            ? genericMethod.GetGenericArguments()
            : null;
        var offset = 0;
        while (offset < il.Length)
        {
            var opCode = il[offset++] == 0xfe
                ? doubleByteOpCodes[il[offset++]]
                : singleByteOpCodes[il[offset - 1]];
            switch (opCode.OperandType)
            {
                case OperandType.InlineMethod:
                case OperandType.InlineField:
                case OperandType.InlineType:
                case OperandType.InlineTok:
                    {
                        var token = BitConverter.ToInt32(il, offset);
                        offset += 4;
                        MemberInfo? member = null;
                        try
                        {
                            member = opCode.OperandType switch
                            {
                                OperandType.InlineMethod => module.ResolveMethod(token, typeArguments, methodArguments),
                                OperandType.InlineField => module.ResolveField(token, typeArguments, methodArguments),
                                OperandType.InlineType => module.ResolveType(token, typeArguments, methodArguments),
                                _ => module.ResolveMember(token, typeArguments, methodArguments),
                            };
                        }
                        catch (ArgumentException)
                        {
                            // A token that belongs to an unresolved external generic reference is
                            // not a generated call edge and can be ignored by this graph check.
                        }

                        if (member is not null)
                        {
                            yield return member;
                        }

                        if (opCode.OperandType == OperandType.InlineMethod && member is MethodBase referenced)
                        {
                            yield return referenced;
                        }

                        break;
                    }
                case OperandType.InlineI:
                case OperandType.InlineBrTarget:
                case OperandType.InlineString:
                case OperandType.InlineSig:
                case OperandType.InlineVar:
                    offset += opCode.OperandType == OperandType.InlineVar ? 2 : 4;
                    break;
                case OperandType.ShortInlineI:
                case OperandType.ShortInlineBrTarget:
                case OperandType.ShortInlineVar:
                    offset += 1;
                    break;
                case OperandType.InlineI8:
                case OperandType.InlineR:
                    offset += 8;
                    break;
                case OperandType.ShortInlineR:
                    offset += 4;
                    break;
                case OperandType.InlineSwitch:
                    {
                        var count = BitConverter.ToInt32(il, offset);
                        offset += 4 + (count * 4);
                        break;
                    }
            }
        }
    }

    private static ISourceGenerator[] CreateGenerators()
    {
        return
        [
            new TestMetadataGenerator().AsSourceGenerator(),
            new HookMetadataGenerator().AsSourceGenerator(),
            new PropertyInjectionSourceGenerator().AsSourceGenerator(),
            new AotConverterGenerator().AsSourceGenerator(),
            new InfrastructureGenerator().AsSourceGenerator(),
            new DynamicTestsGenerator().AsSourceGenerator(),
            new StaticPropertyInitializationGenerator().AsSourceGenerator(),
        ];
    }
}
