using System.Collections.Immutable;
using System.Reflection;
using System.Reflection.Emit;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using TUnit.Core.SourceGenerator.CodeGenerators;
using TUnit.Core.SourceGenerator.Generators;
using TUnit.Core.SourceGenerator.Tests.Extensions;

namespace TUnit.Core.SourceGenerator.Tests;

internal sealed class GeneratedEntryPointContractTests
{
    [Test]
    public async Task DesktopModePreservesRegistrationWithoutPublicCatalogRoot()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class DirectCatalogFixture
            {
                [Test]
                public void RunsDirectly() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "GeneratedEntryPointContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            CreateGenerators(),
            parseOptions: new CSharpParseOptions(LanguageVersion.Preview));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var allGenerated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));

        await Assert.That(allGenerated).DoesNotContain("class GeneratedTestEntryPoint");
        await Assert.That(allGenerated).Contains("SourceRegistrar.RegisterEntries");
        await Assert.That(allGenerated).Contains("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("GetGeneratedCases");
        await Assert.That(allGenerated).DoesNotContain("GeneratedTestCase<");
    }

    [Test]
    public async Task ClosedWorldModeOmitsDesktopRegistrationArtifacts()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class ClosedWorldFixture
            {
                [Test]
                public void RunsDirectly() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var generated = generatedCompilation.SyntaxTrees
            .Select(static tree => tree.GetText().ToString())
            .Where(static text => text.Contains("// <auto-generated/>", StringComparison.Ordinal))
            .ToArray();
        var allGenerated = string.Join(Environment.NewLine, generated);

        await Assert.That(allGenerated).Contains("CreateDirectCatalog");
        await Assert.That(allGenerated).DoesNotContain("SourceRegistrar");
        await Assert.That(allGenerated).DoesNotContain("Sources.TestEntries");
        await Assert.That(allGenerated).DoesNotContain("ConcurrentDictionary");
        await Assert.That(allGenerated).DoesNotContain("Activator.CreateInstance");
        await Assert.That(allGenerated).DoesNotContain("GetGenericTypeDefinition");
        await Assert.That(allGenerated).DoesNotContain("Type.Name");
        await Assert.That(allGenerated).DoesNotContain("Type.FullName");
        await Assert.That(allGenerated).DoesNotContain("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("MethodMetadata");
        await Assert.That(allGenerated).DoesNotContain("ClassMetadata");
        await Assert.That(allGenerated).DoesNotContain("AsyncConvert");
    }

    [Test]
    public async Task ClosedWorldRootCallGraphUsesTypedCaseDelegates()
    {
        const string source = """
            using TUnit.Core;
            namespace TestProject;
            public sealed class DirectCallGraphFixture
            {
                [Test]
                [Arguments(7)]
                public void Case(long value) { }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var entryPoint = build.Assembly.GetType("TUnit.Generated.GeneratedTestEntryPoint")!;
        var directCatalog = (ITestEntryCatalog) entryPoint
            .GetMethod("GetCatalog", BindingFlags.Public | BindingFlags.Static)!
            .Invoke(null, null)!;
        await Assert.That(directCatalog.GetGeneratedCases()).IsNotEmpty();
        var roots = new MethodBase[]
        {
            entryPoint.GetMethod("GetCatalog", BindingFlags.Public | BindingFlags.Static)!,
            entryPoint.GetMethod("CreateDirectCatalog", BindingFlags.NonPublic | BindingFlags.Static)!,
            entryPoint.TypeInitializer!,
        };
        var visited = new HashSet<MethodBase>();
        var pending = new Queue<MethodBase>(roots);
        var forbidden = new List<string>();

        while (pending.Count > 0)
        {
            var method = pending.Dequeue();
            if (!visited.Add(method))
            {
                continue;
            }

            foreach (var member in GetReferencedMembers(method))
            {
                var identity = member switch
                {
                    Type type => type.FullName ?? type.Name,
                    MethodBase referencedMethod => referencedMethod.DeclaringType?.FullName + "." + referencedMethod.Name,
                    _ => member.DeclaringType?.FullName + "." + member.Name,
                };
                if (IsDesktopActivationSymbol(identity))
                {
                    forbidden.Add(identity);
                }

                if (member is MethodBase referenced && referenced.DeclaringType?.Assembly == build.Assembly)
                {
                    pending.Enqueue(referenced);
                }
            }
        }

        await Assert.That(forbidden).IsEmpty()
            .Because(string.Join(Environment.NewLine, forbidden));
    }

    [Test]
    public async Task ClosedWorldGenericAndMultiMethodSourcesCompileAsDirectCases()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            [GenerateGenericTest(typeof(int))]
            [GenerateGenericTest(typeof(string))]
            public sealed class GenericCatalogFixture<T>
            {
                [Test]
                public void First() { }

                [Test]
                public void Second() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldGenericCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var allGenerated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));
        await Assert.That(allGenerated).Contains("GeneratedTestCase<global::TestProject.GenericCatalogFixture<int>>");
        await Assert.That(allGenerated).Contains("GeneratedTestCase<global::TestProject.GenericCatalogFixture<string>>");
        await Assert.That(allGenerated).Contains("First");
        await Assert.That(allGenerated).Contains("Second");
        await Assert.That(allGenerated).DoesNotContain("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("MethodMetadata");
        await Assert.That(allGenerated).DoesNotContain("ClassMetadata");
        await Assert.That(allGenerated).DoesNotContain("SourceRegistrar");
        await Assert.That(allGenerated).DoesNotContain("Activator.CreateInstance");
    }

    [Test]
    public async Task DesktopGenericSourcesRemainInTheUpstreamRegistrationPipeline()
    {
        const string source = """
            using TUnit.Core;
            namespace TestProject;
            [GenerateGenericTest(typeof(int))]
            [GenerateGenericTest(typeof(string))]
            public sealed class DesktopGenericCatalogFixture<T>
            {
                [Test]
                public void First() { }

                [Test]
                public void Second() { }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: false);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases).IsEmpty();
        await Assert.That(build.Assembly.GetType("TUnit.Generated.GeneratedTestEntryPoint")).IsNull();
    }

    [Test]
    public async Task ClosedWorldRootReferencesInheritedSourcesWithoutDirectTests()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public class BaseCatalogFixture
            {
                [Before(HookType.Class)]
                public static void BaseClassSetup() { }

                [After(HookType.Class)]
                public static void BaseClassTeardown() { }

                [Test]
                public void InheritedCase() { }
            }

            [InheritsTests]
            public sealed class DerivedCatalogFixture : BaseCatalogFixture
            {
                [Before(HookType.Class)]
                public static void DerivedClassSetup() { }

                [After(HookType.Class)]
                public static void DerivedClassTeardown() { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldInheritedCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var entryPoint = generatedCompilation.SyntaxTrees
            .Select(static tree => tree.GetText().ToString())
            .Single(static text => text.Contains("class GeneratedTestEntryPoint", StringComparison.Ordinal));
        await Assert.That(entryPoint).Contains("DerivedCatalogFixture");
        await Assert.That(entryPoint).Contains("InheritedCase");

        var generated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees
                .Select(static tree => tree.GetText().ToString())
                .Where(static text => text.Contains("global::TestProject.DerivedCatalogFixture", StringComparison.Ordinal)));
        await Assert.That(generated.IndexOf("BaseClassSetup", StringComparison.Ordinal))
            .IsLessThan(generated.IndexOf("DerivedClassSetup", StringComparison.Ordinal));
        await Assert.That(generated.IndexOf("DerivedClassTeardown", StringComparison.Ordinal))
            .IsLessThan(generated.IndexOf("BaseClassTeardown", StringComparison.Ordinal));
        await Assert.That(generated.IndexOf("GeneratedLifecycleStage.ClassSetup", StringComparison.Ordinal))
            .IsLessThan(generated.IndexOf("GeneratedLifecycleStage.ClassTeardown", StringComparison.Ordinal));
        await Assert.That(generated).Contains("\"global::TestProject.DerivedCatalogFixture\"");
    }

    [Test]
    public async Task ClosedWorldReportsUnsupportedAuthoredCapabilities()
    {
        const string source = """
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using TUnit.Core;
            using TUnit.Core.Interfaces;

            [assembly: ClassConstructor(typeof(object))]

            namespace TestProject;

            public sealed class UnsupportedCatalogFixture
            {
                [Test]
                [MethodDataSource(nameof(Data))]
                public void RuntimeData(int value) { }

                [Test]
                public CustomAwaitable CustomAwaitable() => new();

                [Test]
                [Arguments(1)]
                public void Narrowing(byte value) { }

                [Test]
                [Skip("unsupported")]
                [Explicit]
                [Retry(1)]
                [Timeout(100)]
                [ParallelGroup("unsupported")]
                public void UnsupportedExecutionSemantics() { }

                [Test]
                [FutureSemantic]
                public void FutureSemanticCase() { }

                [Before(HookType.Test)]
                public void ContextHook(TestContext context) { }

                [Before(HookType.Test)]
                public void UnsupportedHookParameter(string value) { }

                [Before(HookType.Assembly)]
                public static void AssemblyHook() { }

                [BeforeEvery(HookType.Test)]
                public static void GlobalHook() { }

                [DynamicTestBuilder]
                public void DynamicBuilder() { }

                [MethodDataSource(nameof(Data))]
                public int Injected { get; set; }

                [Arguments(2)]
                public int ArgumentInjected { get; set; }

                [Arguments(3)]
                public static int StaticArgumentInjected { get; set; }

                public static IEnumerable<int> Data() => new[] { 1 };
            }

            public sealed class CustomAwaitable { }

            [ClassDataSource(typeof(RuntimeClassData))]
            public sealed class RuntimeClassDataFixture { }

            public sealed class RuntimeClassData { }

            public sealed class InitializableFixture : IAsyncInitializer
            {
                public Task InitializeAsync() => Task.CompletedTask;
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
            public sealed class FutureSemanticAttribute : global::TUnit.Core.TUnitAttribute;
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldUnsupportedCatalogContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(static diagnostic => diagnostic.ToString())
            .ToArray();
        var generated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));

        await Assert.That(errors.Any(static error => error.Contains("Runtime data source", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("return void, Task, or ValueTask", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("TestContext or ClassHookContext", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("may only inject CancellationToken", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Dynamic test builders", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Property data injection", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Assembly, test-session", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Global lifecycle hooks", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Runtime class data source", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("IAsyncInitializer", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Assembly-level runtime class construction", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("Argument conversion", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("TUnit semantic attribute 'SkipAttribute'", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("TUnit semantic attribute 'RetryAttribute'", StringComparison.Ordinal))).IsTrue();
        await Assert.That(errors.Any(static error => error.Contains("TUnit semantic attribute 'FutureSemanticAttribute'", StringComparison.Ordinal))).IsTrue();
        await Assert.That(generated).DoesNotContain("AsyncConvert");
        await Assert.That(generated).Contains("Generated catalog supports only void, Task, and ValueTask");
    }

    [Test]
    public async Task ClosedWorldAllowsExactAndImplicitConstantArguments()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class SupportedArgumentsFixture
            {
                [Test]
                [Arguments(1)]
                public void Widening(long value) { }

                [Test]
                [Arguments("ready")]
                public void Text(string value) { }

                [Test]
                [Arguments(null)]
                public void Nullable(string? value) { }

                [Test]
                [Arguments(Mode.First)]
                public void Enum(Mode value) { }

            }

            public enum Mode
            {
                First,
            }
            """;

        var compilation = CSharpCompilation.Create(
                "ClosedWorldSupportedArgumentsContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
                CreateGenerators(),
                parseOptions: new CSharpParseOptions(LanguageVersion.Preview))
            .WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));
    }

    [Test]
    public async Task ClosedWorldPreservesOptionalArgumentDefaults()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class OptionalMethodFixture
            {
                [Test]
                [Arguments()]
                public void MethodDefault(int value = 17)
                {
                    if (value != 17) throw new System.InvalidOperationException();
                }
            }

            [Arguments()]
            public sealed class OptionalConstructorFixture(int value = 17)
            {
                [Test]
                public void ConstructorDefault()
                {
                    if (value != 17) throw new System.InvalidOperationException();
                }
            }

            [Arguments(3, 4)]
            public sealed class ParamsConstructorFixture(params int[] values)
            {
                [Test]
                public void ConstructorParams()
                {
                    if (values.Length != 2 || values[0] != 3 || values[1] != 4)
                        throw new System.InvalidOperationException();
                }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases.Count).IsEqualTo(3);
        foreach (var testCase in cases)
        {
            await testCase.ExecuteAsync();
        }
    }

    [Test]
    public async Task ClosedWorldEmitsTypedArgumentsRowsForMethodAndClassForms()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class TypedMethodArgumentsFixture
            {
                [Test]
                [Arguments<int>(7)]
                public void MethodValue(int value)
                {
                    if (value != 7) throw new System.InvalidOperationException("method value was not emitted");
                }
            }

            [Arguments<string>("ready")]
            public sealed class TypedConstructorArgumentsFixture(string value)
            {
                [Test]
                public void ConstructorValue()
                {
                    if (value != "ready") throw new System.InvalidOperationException("constructor value was not emitted");
                }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases.Count).IsEqualTo(2);
        foreach (var testCase in cases)
        {
            await testCase.ExecuteAsync();
        }
    }

    [Test]
    public async Task ClosedWorldPreservesMethodDisplayNameAndRowSubstitution()
    {
        const string source = """
            using TUnit.Core;

            namespace TestProject;

            public sealed class DisplayNameFixture
            {
                [Test]
                [DisplayName("Date $arg1 $value $valued $arg3")]
                [Arguments(7, DisplayName = "row display must lose")]
                public void Case(int value) { }

                [Test]
                [Arguments("x", 2, DisplayName = "row $arg1/$arg2/$arg3/$arg1x/$first/$second/$firstExtra")]
                public void RowDisplay(string first, int second) { }
            }

            [DisplayName("Class $text $arg1")]
            [Arguments("ready", DisplayName = "constructor row must lose")]
            public sealed class ClassDisplayNameFixture(string text)
            {
                [Test]
                public void Case() { }
            }

            [Arguments("ready", DisplayName = "constructor row $arg1/$text")]
            public sealed class ConstructorRowDisplayNameFixture(string text)
            {
                [Test]
                [Arguments(3)]
                public void Case(int value) { }
            }
            """;

        var build = BuildGeneratedCatalog(source, closedWorld: true);
        var cases = build.Catalog.GetGeneratedCases();
        await Assert.That(cases.Count).IsEqualTo(4);
        await Assert.That(cases.Select(static testCase => testCase.DisplayName)
                .OrderBy(static displayName => displayName, StringComparer.Ordinal)
                .SequenceEqual(new[]
                {
                    "Class ready $arg1",
                    "Date $arg1 7 7d $arg3",
                    "constructor row 3/$text",
                    "row x/2/$arg3/$arg1x/x/2/$firstExtra",
                }))
            .IsTrue();
    }

    [Test]
    public async Task DesktopModeKeepsConversionBackedArgumentsInTheUpstreamPipeline()
    {
        const string source = """
            using System;
            using TUnit.Core;

            namespace TestProject;

            public sealed class ConversionFixture
            {
                [Test]
                [Arguments("2022-05-31")]
                public void DateTimeFromString(DateTime value) { }
            }
            """;

        var compilation = CSharpCompilation.Create(
                "DesktopConversionContract",
                [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            CreateGenerators(),
            parseOptions: new CSharpParseOptions(LanguageVersion.Preview));
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);

        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        await Assert.That(errors).IsEmpty()
            .Because(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));

        var allGenerated = string.Join(
            Environment.NewLine,
            generatedCompilation.SyntaxTrees.Select(static tree => tree.GetText().ToString()));
        await Assert.That(allGenerated).Contains("SourceRegistrar.RegisterEntries");
        await Assert.That(allGenerated).Contains("TestEntryFactory");
        await Assert.That(allGenerated).DoesNotContain("GetGeneratedCases");
        await Assert.That(allGenerated).DoesNotContain("GeneratedTestCase<");

        using var stream = new MemoryStream();
        var emitResult = generatedCompilation.Emit(stream);
        await Assert.That(emitResult.Success).IsTrue()
            .Because(string.Join(Environment.NewLine,
                emitResult.Diagnostics.Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                    .Select(static diagnostic => diagnostic.ToString())));
    }

    private static GeneratedCatalogBuild BuildGeneratedCatalog(string source, bool closedWorld)
    {
        var compilation = CSharpCompilation.Create(
                closedWorld ? "ClosedWorldCatalogParity" : "DesktopCatalogParity",
                [CSharpSyntaxTree.ParseText(
                    source,
                    new CSharpParseOptions(LanguageVersion.Preview),
                    path: "CatalogParityFixture.cs")],
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .WithReferences(ReferencesHelper.References);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            CreateGenerators(),
            parseOptions: new CSharpParseOptions(LanguageVersion.Preview));
        if (closedWorld)
        {
            driver = driver.WithUpdatedAnalyzerConfigOptions(new TestAnalyzerConfigOptionsProvider(
                ImmutableDictionary<string, string>.Empty.Add(
                    "build_property.TUnitSourceGenerationMode",
                    "ClosedWorldCatalog")));
        }

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var generatedCompilation, out var diagnostics);
        var errors = diagnostics
            .Concat(generatedCompilation.GetDiagnostics())
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        if (errors.Length > 0)
        {
            throw new InvalidOperationException(string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));
        }

        using var stream = new MemoryStream();
        var emitResult = generatedCompilation.Emit(stream);
        if (!emitResult.Success)
        {
            throw new InvalidOperationException(string.Join(Environment.NewLine,
                emitResult.Diagnostics.Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                    .Select(static diagnostic => diagnostic.ToString())));
        }

        var assembly = System.Reflection.Assembly.Load(stream.ToArray());
        var generatedCases = assembly.GetTypes()
            .Where(static type => type.Namespace == "TUnit.Generated")
            .SelectMany(static type => type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                .Where(static method => method.Name == "GetGeneratedCases" &&
                                        method.ReturnType == typeof(GeneratedTestCase[])))
            .SelectMany(static method => (GeneratedTestCase[]) method.Invoke(null, null)!)
            .ToArray();

        return new GeneratedCatalogBuild(
            assembly,
            new SourceGeneratedTestCatalog(generatedCases, "TUnit.Core.SourceGenerator"));
    }

    private static async Task<string[]> ExecuteCatalog(SourceGeneratedTestCatalog catalog)
    {
        var results = new List<string>();
        foreach (var testCase in catalog.GetGeneratedCases())
        {
            try
            {
                await testCase.ExecuteAsync();
                results.Add($"{testCase.StableId}:Passed");
            }
            catch (Exception exception)
            {
                results.Add($"{testCase.StableId}:{exception.GetType().Name}");
            }
        }

        return results.ToArray();
    }

    private static string DescribeCase(GeneratedTestCase testCase)
    {
        var arguments = string.Join(",", testCase.Arguments.Select(static argument =>
            argument switch
            {
                null => "null",
                string text => text,
                _ => Convert.ToString(argument, System.Globalization.CultureInfo.InvariantCulture) ?? "null",
            }));
        var lifecycle = string.Join(",", testCase.Lifecycle.Actions.Select(static action => $"{action.Stage}:{action.Order}"));
        return string.Join("|", testCase.StableId, testCase.DisplayName, testCase.GroupIdentity,
            testCase.InvocationKind, testCase.CompletionPolicy, testCase.CatalogProvenance, arguments, lifecycle);
    }

    private sealed record GeneratedCatalogBuild(System.Reflection.Assembly Assembly, SourceGeneratedTestCatalog Catalog);

    private static bool IsDesktopActivationSymbol(string identity)
    {
        return identity.Contains("CastHelper", StringComparison.Ordinal) ||
               identity.Contains("Activator", StringComparison.Ordinal) ||
               identity.Contains("ConcurrentDictionary", StringComparison.Ordinal) ||
               identity.Contains("MethodInfo", StringComparison.Ordinal) ||
               identity.Contains("System.Reflection", StringComparison.Ordinal) ||
               identity.Contains("DynamicInvoke", StringComparison.Ordinal) ||
               identity.Contains("SourceRegistrar", StringComparison.Ordinal) ||
               identity.Contains("TestEntryFactory", StringComparison.Ordinal) ||
               identity.Contains("MethodMetadata", StringComparison.Ordinal) ||
               identity.Contains("ClassMetadata", StringComparison.Ordinal) ||
               identity.Contains("AsyncConvert", StringComparison.Ordinal);
    }

    private static IEnumerable<MemberInfo> GetReferencedMembers(MethodBase method)
    {
        var body = method.GetMethodBody();
        var il = body?.GetILAsByteArray();
        if (il is null)
        {
            yield break;
        }

        var singleByteOpCodes = new OpCode[0x100];
        var doubleByteOpCodes = new OpCode[0x100];
        foreach (var field in typeof(OpCodes).GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            if (field.GetValue(null) is not OpCode opCode)
            {
                continue;
            }

            var value = unchecked((ushort) opCode.Value);
            if (value < 0x100)
            {
                singleByteOpCodes[value] = opCode;
            }
            else if ((value & 0xff00) == 0xfe00)
            {
                doubleByteOpCodes[value & 0xff] = opCode;
            }
        }

        var module = method.Module;
        var typeArguments = method.DeclaringType?.IsGenericType == true
            ? method.DeclaringType.GetGenericArguments()
            : null;
        var methodArguments = method is MethodInfo { IsGenericMethod: true } genericMethod
            ? genericMethod.GetGenericArguments()
            : null;
        var offset = 0;
        while (offset < il.Length)
        {
            var opCode = il[offset++] == 0xfe
                ? doubleByteOpCodes[il[offset++]]
                : singleByteOpCodes[il[offset - 1]];
            switch (opCode.OperandType)
            {
                case OperandType.InlineMethod:
                case OperandType.InlineField:
                case OperandType.InlineType:
                case OperandType.InlineTok:
                    {
                        var token = BitConverter.ToInt32(il, offset);
                        offset += 4;
                        MemberInfo? member = null;
                        try
                        {
                            member = opCode.OperandType switch
                            {
                                OperandType.InlineMethod => module.ResolveMethod(token, typeArguments, methodArguments),
                                OperandType.InlineField => module.ResolveField(token, typeArguments, methodArguments),
                                OperandType.InlineType => module.ResolveType(token, typeArguments, methodArguments),
                                _ => module.ResolveMember(token, typeArguments, methodArguments),
                            };
                        }
                        catch (ArgumentException)
                        {
                            // A token that belongs to an unresolved external generic reference is
                            // not a generated call edge and can be ignored by this graph check.
                        }

                        if (member is not null)
                        {
                            yield return member;
                        }

                        if (opCode.OperandType == OperandType.InlineMethod && member is MethodBase referenced)
                        {
                            yield return referenced;
                        }

                        break;
                    }
                case OperandType.InlineI:
                case OperandType.InlineBrTarget:
                case OperandType.InlineString:
                case OperandType.InlineSig:
                case OperandType.InlineVar:
                    offset += opCode.OperandType == OperandType.InlineVar ? 2 : 4;
                    break;
                case OperandType.ShortInlineI:
                case OperandType.ShortInlineBrTarget:
                case OperandType.ShortInlineVar:
                    offset += 1;
                    break;
                case OperandType.InlineI8:
                case OperandType.InlineR:
                    offset += 8;
                    break;
                case OperandType.ShortInlineR:
                    offset += 4;
                    break;
                case OperandType.InlineSwitch:
                    {
                        var count = BitConverter.ToInt32(il, offset);
                        offset += 4 + (count * 4);
                        break;
                    }
            }
        }
    }

    private static ISourceGenerator[] CreateGenerators()
    {
        return
        [
            new TestMetadataGenerator().AsSourceGenerator(),
            new HookMetadataGenerator().AsSourceGenerator(),
            new PropertyInjectionSourceGenerator().AsSourceGenerator(),
            new AotConverterGenerator().AsSourceGenerator(),
            new InfrastructureGenerator().AsSourceGenerator(),
            new DynamicTestsGenerator().AsSourceGenerator(),
            new StaticPropertyInitializationGenerator().AsSourceGenerator(),
        ];
    }
}
