<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsTestingPlatformApplication>true</IsTestingPlatformApplication>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>$(NoWarn);CA1859</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="18.0.1" />
    <PackageReference Include="NetWasm.Hosting" Version="[0.1.0-rc.1]" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../NetWasm.TUnit.Runner/NetWasm.TUnit.Runner.csproj" />
    <ProjectReference Include="../NetWasm.TUnit.VSTest.Adapter/NetWasm.TUnit.VSTest.Adapter.csproj" />
  </ItemGroup>
</Project>
