<Project Sdk="NetWasm.Sdk">
  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net10.0;netwasm0.1</TargetFrameworks>
    <AssemblyName>NetWasm.TUnit.Runner</AssemblyName>
    <RootNamespace>NetWasm.TUnit.Runner</RootNamespace>
    <IsPackable>false</IsPackable>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateRepositoryUrlAttribute>false</GenerateRepositoryUrlAttribute>
    <EnableTUnitSourceGeneration>false</EnableTUnitSourceGeneration>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Build/NetWasm.TUnit.Program.cs" />
    <PackageReference Include="NetWasm.TUnit.Core" Version="[$(NetWasmTUnitPackageVersion)]" />
    <PackageReference Include="NetWasm.TUnit.Assertions" Version="[$(NetWasmTUnitPackageVersion)]" />
  </ItemGroup>
</Project>
